name: Deploy Portafolio CV

on:
  push:
    branches: [ master ] # Se activa cada vez que hagas push a master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 1033
          script: |
            cd ~/www/portafolio-cv
            git pull origin master
            npm install
            npm run build
            pm2 restart portafolio-cv || pm2 start npm --name "portafolio-cv" -- start